/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Cliente_Servidor.Servidor.Servidor;

/**
 *
 * @author Personal
 */
public class GUIServidor extends javax.swing.JFrame {

    /**
     * Creates new form GUIServidor
     */
    Servidor servidor;
    public GUIServidor() {
        initComponents();
        this.servidor = new Servidor(9999, this);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        spinnerCtdJugadores = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusServidor = new javax.swing.JTextArea();
        btnStop = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStart.setBackground(new java.awt.Color(0, 0, 0));
        btnStart.setForeground(new java.awt.Color(102, 102, 0));
        btnStart.setText("Iniciar Partida");
        btnStart.setOpaque(false);
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        jPanel1.add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 46, 165, 26));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 233, -1, -1));

        spinnerCtdJugadores.setModel(new javax.swing.SpinnerNumberModel(2, 2, 4, 1));
        spinnerCtdJugadores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(spinnerCtdJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 46, 52, -1));

        statusServidor.setBackground(new java.awt.Color(0, 0, 0));
        statusServidor.setColumns(20);
        statusServidor.setForeground(new java.awt.Color(102, 102, 0));
        statusServidor.setRows(5);
        jScrollPane1.setViewportView(statusServidor);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 188, 347, 188));

        btnStop.setBackground(new java.awt.Color(0, 0, 0));
        btnStop.setForeground(new java.awt.Color(102, 102, 0));
        btnStop.setText("Detener Servidor");
        btnStop.setOpaque(false);
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });
        jPanel1.add(btnStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 165, 27));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 400));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Resources/server.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        int eleccion = Integer.valueOf(spinnerCtdJugadores.getValue().toString());

        // Cliente dice cuantos jugadores?? o eso esta en el server?
        //CUALQUIERA SE DEBE USAR ESTO PARA SABER LA OPCION DEL COMBOBOX
        servidor.setNumeroClientes(eleccion);
        servidor.start();
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIServidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinnerCtdJugadores;
    private javax.swing.JTextArea statusServidor;
    // End of variables declaration//GEN-END:variables

    public void addStatus(String mensaje) {
       statusServidor.append(mensaje + "\n");
    }
}
